import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Red",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="overflow-x-hidden">
        <div className="w-full flex flex-col items-center">
          <Header />
          <div className="w-full max-w-[1980px] px-[20px] xl:px-[120px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
