import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Red",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <div className="w-full flex justify-center flex-col px-[120px]">
          <Header />
          <div className="w-full max-w-[1980px] mt-[40px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
