import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Red",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="">
        <div className="w-full flex justify-center px-[40px] 2xl:px-[120px]">
          <div className="w-full max-w-[1980px]">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
